### PR TITLE
Add e2e tests for logs API

### PR DESCRIPTION
**Pull request by sayan-biswas**
# Changes

Add e2e test for ListLogs, GetLog, DeleteLog using gRPC and REST.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you review them:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] [Tested your changes locally](https://github.com/tektoncd/results/blob/main/docs/DEVELOPMENT.md) (if this is a code change)
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user-facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contain the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by enarha** [comment]
@sayan-biswas is that still WIP? Anything is blocking it?

**Comment by sayan-biswas** [comment]
@enarha This is still in progress. One test to verify the content of the file stored vs the actual log, is pending. Haven't worked on it lately due to some other issues. Will start working on this again.

**Review by khrm — COMMENTED** [review]
Do we need to reopen this? @sayan-biswas

**Pull request closed without merging**
