### PR TITLE
Disable Proxy for Rest to GRPC communication

### PR DESCRIPTION
**Pull request by khrm**
This is internal communication and proxy isn't needed. Also, GRPC is HTTP/2 and using proxy can cause problem as some of the proxies are HTTP/1.1.

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you review them:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] [Tested your changes locally](https://github.com/tektoncd/results/blob/main/docs/DEVELOPMENT.md) (if this is a code change)
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [ ] Has a kind label. You can add a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user-facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contain the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/kind bug

**Comment by khrm** [comment]
This is already shipped in OpenShift Pipelines and we didn't face any issues from the customers. So this approach is correct. Proxy between Rest and GRPC server isn't needed. It's just an internal call.

**Review by sayan-biswas — APPROVED** [review]

**Review by khrm — COMMENTED** [review]
/cherry-pick @release-v0.9.0x

**Pull request merged**
