### PR TITLE
Upgrade sql-initdb-config ConfigMap

### PR DESCRIPTION
**Pull request by alan-ghelardi**
This pull request resolves https://github.com/tektoncd/results/issues/289 by
upgrading the sql-initdb-config ConfigMap to install the latest schema.

## Note

I deleted the generate.go in favor of using Kustomize's ConfigMap
generators. The motivation is avoiding duplication since in the current approach
both files, result.sql and 100-sql-initdb-config.yaml, should be generated and
committed to ensure that the correct schema will be installed on the database
initialization. The new approach seems to be simpler: now only the results.sql
file need to be updated once the database schema changes and the
sql-initdb-config ConfigMap will be generated in runtime once the kustomization
manifest is processed.

### CODE REVIEW

**Comment by dibyom** [comment]
(minor) Is it possible to keep the results.sql in the schema folder while still using kustomize configmap generator?

**Comment by alan-ghelardi** [comment]
@dibyom  it is, but Kustomize, by default, forbids the kustomization file from referencing files from outside their root folder. To disable this restriction, users need to pass the `--load-restrictor=LoadRestrictionsNone` while building the kustomization file. Usually, this isn't recommended, that's why I moved the results.sql to the config folder.
Do you think that there're benefits in keeping the file under the schema directory? If so, maybe we could create a symblink from schema/results.sql to config/results.sql?

**Comment by alan-ghelardi** [comment]
@dibyom  any thoughts on that?

**Comment by adambkaplan** [comment]
I am personally OK with keeping the sql in the `config` Kustomization directory. Do we have mechanisms to sync the .sql contents with the GORM model?

**Comment by dibyom** [comment]
hi @alan-ghelardi if we could symlink the file to config, that'd be ideal. But if not, I'm ok moving it to config (do we need to update any docs anywhere?)

**Comment by alan-ghelardi** [comment]
@adambkaplan  and @dibyom I was wondering if we could simply remove this schema and let Gorm run the auto-migration by default, giving the option of disabling it if people prefer. I described this in more details at https://github.com/tektoncd/results/issues/311.
I googled a bit, and didn't find a way of extracting the DDL script from Gorm models. So, I'd suggest removing the file and adjusting the models to reflect the most recent schema. Do you people see any strong argument for keeping this file with the burden of keeping it up to date with the models?

**Comment by dibyom** [comment]
+1 to making the migration optional.

I think we started with the sql file first and then migrated to Gorm. I'm not sure if there is any historical reason for keeping both. I think in the beginning we used SQLite as the DB and later shifted to Postgres - does GORM support jsonb?

**Comment by adambkaplan** [comment]
likewise +1 on ability to disable auto-migration as well. May be nice to have a sub-command (or separate binary) that lets the migrator be run as a `Job` externally from the apiserver.

**Comment by alan-ghelardi** [comment]
I started looking into that more deeply and after making a few adjustments in the models, I managed to get tests working without installing the schema directly and letting Gorm to run the auto-migration. Actually, there are two tests failing (those that verify if the same objects cannot be inserted twice). Maybe some uniqueness constraint is missing. I'm gonna fix it and will open a pr.

**Comment by dibyom** [comment]
I think we can close this out now? in favor of #334 ?

**Pull request closed without merging**
