### PR TITLE
Bump tkn-results to use latest version of results

### PR DESCRIPTION
**Pull request by avinal**
# Changes

- go1.17 support has already ended, bump tkn-results to 1.19
- replace deprecated methods
- bump results version in tkn-results

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you review them:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] [Tested your changes locally](https://github.com/tektoncd/results/blob/main/docs/DEVELOPMENT.md) (if this is a code change)
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user-facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [x] Release notes contain the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
- tkn-results bumped to use v0.7.0 of results
- tkn-results Go version bumped to go1.19
```

### CODE REVIEW

**Comment by adambkaplan** [comment]
@avinal two commits makes the most sense:

- First commit - update to go 1.19, run `go mod tidy && go mod vendor`
- Second commit - refactors related to code updates.

**Comment by avinal** [comment]
I did not run `go mod vendor` for `tkn-results`. It is currently not in the main tree and many dependencies will be duplicated. Filed #551 for moving in tree.

**Review by khrm — COMMENTED** [review]
We need to merge older prs of cli.

**Review by vdemeester — APPROVED** [review]
@avinal needs a small rebase

**Comment by avinal** [comment]
Hey Vincent, we are holding this PR until other CLI prs are merged. I will rebase as soon they are meregd.

**Comment by avinal** [comment]
I have tested the bump with the latest changes in tkn-results, everything is working as expected. PTAL

**Review by khrm — COMMENTED** [review]
/lgtm

**Pull request merged**
