### PR TITLE
do not lose flush error on server side update log

### PR DESCRIPTION
**Pull request by gabemontero**
# Changes

/kind bug

An intermittent server side update log error I discussed with @sayan-biswas @avinal @khrm @enarha last month:

```
{"level":"error","ts":1713278748.4461074,"caller":"v1alpha2/logs.go:103","msg":"operation error S3: UploadPart, https response error StatusCode: 404, RequestID: 732R1N8N4J9RSB06, HostID: lsBFw/50Pfgee1X946YoNjrGdEfnafH1KmsVxQdqZXNGqNDuk2Vdka8vSm13Kx3h88Vbyq9HM7A=, api error NoSuchUpload: The specified upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.","stacktrace":
"github.com/tektoncd/results/pkg/api/server/v1alpha2.(*Server).UpdateLog.func1\n
\t/opt/app-root/src/pkg/api/server/v1alpha2/logs.go:103\n
github.com/tektoncd/results/pkg/api/server/v1alpha2.(*Server).UpdateLog\n
\t/opt/app-root/src/pkg/api/server/v1alpha2/logs.go:156\n
github.com/tektoncd/results/proto/v1alpha2/results_go_proto._Logs_UpdateLog_Handler\n
\t/opt/app-root/src/proto/v1alpha2/results_go_proto/api_grpc.pb.go:686\n
github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/recovery.StreamServerInterceptor.func1\n\t/opt/app-root/src/vendor/github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/recovery/interceptors.go:48\n
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1\n
\t/opt/app-root/src/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:49\n
github.com/grpc-ecosystem/go-grpc-prometheus.(*ServerMetrics).StreamServerInterceptor.func1\n
\t/opt/app-root/src/vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server_metrics.go:121\n
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1\n
\t/opt/app-root/src/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:49\n
github.com/grpc-ecosystem/go-grpc-middleware/auth.StreamServerInterceptor.func1\n
\t/opt/app-root/src/vendor/github.com/grpc-ecosystem/go-grpc-middleware/auth/auth.go:66\n
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1\n
\t/opt/app-root/src/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:49
\ngithub.com/grpc-ecosystem/go-grpc-middleware/logging/zap.StreamServerInterceptor.func1\n
\t/opt/app-root/src/vendor/github.com/grpc-ecosystem/go-grpc-middleware/logging/zap/server_interceptors.go:53\n
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1\n
\t/opt/app-root/src/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:49\n
github.com/grpc-ecosystem/go-grpc-middleware/tags.StreamServerInterceptor.func1\n
\t/opt/app-root/src/vendor/github.com/grpc-ecosystem/go-grpc-middleware/tags/interceptors.go:39\n
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1.1.1\n
\t/opt/app-root/src/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:49\n
github.com/grpc-ecosystem/go-grpc-middleware.ChainStreamServer.func1\n
\t/opt/app-root/src/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:58\n
google.golang.org/grpc.(*Server).processStreamingRPC\n
\t/opt/app-root/src/vendor/google.golang.org/grpc/server.go:1673\n
google.golang.org/grpc.(*Server).handleStream\n
\t/opt/app-root/src/vendor/google.golang.org/grpc/server.go:1787\ngoogle.golang.org/grpc.(*Server).serveStreams.func2.1\n
\t/opt/app-root/src/vendor/google.golang.org/grpc/server.go:1016"}
```

If we get an error on the flush let's return it to the client in case retry is possible

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you review them:

- [n/a ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ n/a] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ /] [Tested your changes locally](https://github.com/tektoncd/results/blob/main/docs/DEVELOPMENT.md) (if this is a code change)
- [/ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [/ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [/ ] Has a kind label. You can add a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ n/a] Release notes block below has been updated with any user-facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ n/a] Release notes contain the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/lgtm

**Comment by enarha** [comment]
It feels to me that we are masking the "real" error which got us to `handleReturn` in the first place. I mean when we try to flush the log and fail. Maybe at least concatenate the error messages like "got flushErr while handling otherError"?

**Comment by gabemontero** [comment]
> It feels to me that we are masking the "real" error which got us to `handleReturn` in the first place. I mean when we try to flush the log and fail. Maybe at least concatenate the error messages like "got flushErr while handling otherError"?

yeah I was wondering about that as well after I submitted the PR @enarha .... I'll look into doing this.  Will post a comment when I 've updated it.

**Comment by gabemontero** [comment]
> > It feels to me that we are masking the "real" error which got us to `handleReturn` in the first place. I mean when we try to flush the log and fail. Maybe at least concatenate the error messages like "got flushErr while handling otherError"?
> 
> yeah I was wondering about that as well after I submitted the PR @enarha .... I'll look into doing this. Will post a comment when I 've updated it.

I've updated the PR @enarha to aggregate the errors ... PTAL

**Review by enarha — COMMENTED** [review]
/approve

**Review by khrm — COMMENTED** [review]
/lgtm

**Pull request merged**
