### PR TITLE
Add option to enable prometheus histogram

### LINKED ISSUE #510: Enable prometheus histogram metrics for API server
Currently prometheus histograms are not enabled in the API server, which prevents us from monitoring latency distributions.
Response time latencies are a great way to determine server performance. 

Since this a high cardinality metrics, it is better to keep this optional for users.

### PR DESCRIPTION
**Pull request by sayan-biswas**
Adds a config option `PROMETHEUS_HISTOGRAM` to enable prometheus histogram for the gRPC server. This records metrics to calculate request latency distributions.

resolves #510 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you review them:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] [Tested your changes locally](https://github.com/tektoncd/results/blob/main/docs/DEVELOPMENT.md) (if this is a code change)
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user-facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contain the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
api: Config option `PROMETHEUS_HISTOGRAM` added to enable histograms (disabled by default).
```

### CODE REVIEW

**Comment by enarha** [comment]
/approve
Please add `/kind` label. Personally I'm considering this a feature, but I'm leaving it to you to decide.
My only question is if we really need the `action required` here? With the default option being disabled, users do not strictly require to do anything. They do need to set the configuration option to enable the functionality, but doing nothing changes/breaks nothing.

**Comment by sayan-biswas** [comment]
@enarha Removed "action required". Added kind label to miscellaneous as this change is not much of a feature, and more of enabling a feature which was already there.

**Review by adambkaplan — APPROVED** [review]
/approve

I would consider this a true feature. The "end user" of this histogram is an SRE managing/monitoring Results.

Is it possible to add docs here about the metrics that Results exposes for the apiserver? Perhaps a link to the relevant doc in the grpc-ecosystem repo is sufficient.

**Pull request merged**
