### PR TITLE
Add support for configuring custom query params to Logs API

### PR DESCRIPTION
**Pull request by khrm**
These query params can be sort order or any other params.

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you review them:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] [Tested your changes locally](https://github.com/tektoncd/results/blob/main/docs/DEVELOPMENT.md) (if this is a code change)
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user-facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contain the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
LOGGING_PLUGIN_QUERY_PARAMS can be used to pass custom queries for third-party Logs API.
```

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/kind bug

**Review by khrm — COMMENTED** [review]
/assign @vdemeester @enarha

**Review by vdemeester — APPROVED** [review]

**Review by enarha — COMMENTED** [review]
/lgtm

**Pull request merged**
