### PR TITLE
Access to Results API Service system:authenticated users

### PR DESCRIPTION
**Pull request by khrm**
# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you review them:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] [Tested your changes locally](https://github.com/tektoncd/results/blob/main/docs/DEVELOPMENT.md) (if this is a code change)
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user-facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contain the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/kind feature

**Comment by khrm** [comment]
Fixes #598

**Review by adambkaplan — COMMENTED** [review]
/hold

:thinking: why does the `system:authenticated` user need to see the details of the Tekton Results service?

In a production environment, I would expect the Results API service to be accessed via an `Ingress` object or equivalent. We should explicitly recommend that.

**Comment by khrm** [comment]
Some UI folk told me that they can extrapolate ingress/route using the service.

**Review by khrm — COMMENTED** [review]
On second thought, having access to ingress(or OpenShift's route) via operator is the way to go.
Closing this. @adambkaplan

**Pull request closed without merging**
