### PR TITLE
Refactor reconcilers to use Object interfaces.

### PR DESCRIPTION
**Pull request by wlynch**
This is a prereq for
https://github.com/tektoncd/community/blob/main/teps/0088-result-summaries.md.

This change refactors the reconcilers in order to access objects within Runs
in a generic way using interfaces. Previously we were using
unstructured.Unstructured, which doesn't allow us to use an interface to
access common fields across different Run types (in particular - for
result summaries we need access to the Knative Statuses).

This change should not change any behavior.

Part of #147

### CODE REVIEW

**Review by dibyom — APPROVED** [review]
Looks good - unstructured.Unstructured only allows access to common metadata fields though now we need access to status fields as well - is that why we need this?

**Comment by wlynch** [comment]
> Looks good - unstructured.Unstructured only allows access to common metadata fields though now we need access to status fields as well - is that why we need this?

Yup exactly. The next step is to use the new Object type to extract the status to extract common fields like timestamps, status, etc.

```yaml
type Object interface {
	metav1.Object
	runtime.Object
	StatusConditionGetter
}
```

**Review by khrm — COMMENTED** [review]
/remove-kind feature
/kind cleanup

**Pull request merged**
