### PR TITLE
Remove Config Values as Env var in API server

### LINKED ISSUE #607: Shouldn't set DB_HOST and DB_NAME in Env Variable of release manifest
# Expected Behavior

The user should be able to configure via configmap
# Actual Behavior
The configmap values don't have don't change the results db or name.
These values should come from the config map, not the environment variable so the enduser/operator just need configure the configmap instead of an environment variable.

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

### PR DESCRIPTION
**Pull request by khrm**
Move these config values to the configmap so that changing configmap configures the value.
Fixes #607 

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you review them:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] [Tested your changes locally](https://github.com/tektoncd/results/blob/main/docs/DEVELOPMENT.md) (if this is a code change)
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user-facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contain the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
DB_NAME and DB_HOST should be configurable via configmap.
```

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/kind bug

**Review by khrm — COMMENTED** [review]
/test pull-tekton-results-integration-tests

**Review by avinal — APPROVED** [review]
Tested, works as expected.
/approve

**Review by khrm — COMMENTED** [review]
@xinredhat There's an issue with  `pull-tekton-results-go-coverage` job that was added.

**Review by khrm — COMMENTED** [review]
/retest

**Comment by khrm** [comment]
@xinredhat Go coverage job was fixed.

**Comment by khrm** [comment]
@enarha Let's merge this.

**Comment by khrm** [comment]
@enarha Let's merge this for release also.

**Review by vdemeester — COMMENTED** [review]
/lgtm

**Pull request merged**
