### PR TITLE
v0.1.0 Release.

### PR DESCRIPTION
**Pull request by wlynch**
Note: This is the first **alpha** Results release. We appreciate any feedback you can provide!

What's new:
- v1beta1 Results API
  - Adds CRUD support for storing Results/Records in durable storage.
  - Supports CEL based List filtering for complex queries over data.
  - etag support to ensure stable data writes.
  - Includes deployable Kubernetes Service implementation.
- Results Watcher
  - Kubernetes based implementation for watching TaskRun/PipelineRuns to
  automatically covert into Record data. Records are grouped in Results based
  on derived event identifiers (e.g. Trigger event, PipelineRun ID, etc).

Big thanks to all our contributors that made this happen:
- Andrea Frittoli <andrea.frittoli@gmail.com>
- Billy Lynch <wlynch@google.com>
- Dibyo Mukherjee <dibyajyoti@google.com>
- Jason Hall <jasonhall@google.com>
- Xinru Zhang <xinruzhang@google.com>
- ziweifan <ziweifan@google.com>

### CODE REVIEW

**Review by ImJasonH — COMMENTED** [review]
/lgtm

🎉 🎉 🎉 🎉 🎉

**Review by dibyom — COMMENTED** [review]
Thoughts on creating a GitHub release and putting the file there instead of inside the source tree?

**Comment by wlynch** [comment]
> Thoughts on creating a GitHub release and putting the file there instead of inside the source tree?

That's the next step! :D 

Rough plan is to:
1. Check generated release.yaml into v0.1.x release branch
2. Tag v0.1.x branch as v0.1.0
3. Create GitHub release based off the v0.1.0 tag.
4. Upload release.yaml to GCS

This way the repo also includes the same release information, independent of any GitHub specific features. All the content should be roughly the same.

**Comment by ImJasonH** [comment]
> This way the repo also includes the same release information, independent of any GitHub specific features. All the content should be roughly the same.

I don't have a strong opinion about how this is released, especially at v0.1.0, but it'd probably be nice to have a similar release process as pipeline or triggers, so folks can easily move around projects if they want, and so CI/CD improvements can be applied across them all relatively easily.

The release.yaml is ultimately a release artifact, IMO, that can be derived from source information (+`KO_DOCKER_REPO`, etc.), so I think it makes sense in a GitHub release, even though that means adopting GitHub-specific features.

**Comment by wlynch** [comment]
> it'd probably be nice to have a similar release process as pipeline or triggers, so folks can easily move around projects if they want, and so CI/CD improvements can be applied across them all relatively easily.

Ack. Things are going to be a little different for this release since we don't have the automation set up yet, but I'll try to mirror off of the other repos as much as possible. Closing this out.

**Pull request closed without merging**
