### PR TITLE
fix misspelled word

### PR DESCRIPTION
**Pull request by SimonWaldherr**

### CODE REVIEW

**Comment by dibyom** [comment]
hi @SimonWaldherr  would you mind signing the CLA?

**Comment by SimonWaldherr** [comment]
> hi @SimonWaldherr would you mind signing the CLA?

done 👍

**Review by adambkaplan — APPROVED** [review]
/approve

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Review by khrm — COMMENTED** [review]
/kind misc
We need this label for release as discussed in the last WG call.

**Pull request merged**
