### PR TITLE
Add health checking endpoints to RPC server.

### LINKED ISSUE #45: API Server Health Checking
### Feature request

We should add [gRPC health checking](https://github.com/grpc/grpc/blob/master/doc/health-checking.md) to the API server for interop with other gRPC tooling.

### Use case

This would let us take advantage of other gRPC health check tooling (https://github.com/grpc-ecosystem/grpc-health-probe, grpc_cli, etc.)

### PR DESCRIPTION
**Pull request by wlynch**
See https://github.com/grpc/grpc/blob/master/doc/health-checking.md for
gRPC health checking documentataton.

Fixes #45

### CODE REVIEW

**Comment by ImJasonH** [comment]
/lgtm

Will/can this healthcheck endpoint also be used as a k8s healthcheck to know when to route requests through the service?

**Comment by wlynch** [comment]
> Will/can this healthcheck endpoint also be used as a k8s healthcheck to know when to route requests through the service?

Yes it can! See https://github.com/grpc-ecosystem/grpc-health-probe

**Comment by ImJasonH** [comment]
> > Will/can this healthcheck endpoint also be used as a k8s healthcheck to know when to route requests through the service?
> 
> Yes it can! See https://github.com/grpc-ecosystem/grpc-health-probe

Oh that's kind of gross, it requires the `grpc_health_probe` binary to be included in the image and called with an `exec` probe. 😒 

Since it's not that simple I won't push too hard for it 😄 

Still /lgtm

**Pull request merged**
