### PR TITLE
[CLI] Add integration support to tkn

### PR DESCRIPTION
**Pull request by khrm**
# Changes
Added annotations to support command integration with `tkn`.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you review them:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] [Tested your changes locally](https://github.com/tektoncd/results/blob/main/docs/DEVELOPMENT.md) (if this is a code change)
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user-facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contain the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
tkn-results: add annotations so the cli can be run as tkn plugin.
```

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/kind feature

**Comment by adambkaplan** [comment]
Added a release note - this is an important change that users and developers should know about!

**Comment by adambkaplan** [comment]
We should not block on adding "user friendly" docs. I have filed #475 for this purpose - the docs "meets min" is that the auto-generated docs are synced with code.

**Comment by xinnjie** [comment]
Any progress?

**Review by adambkaplan — APPROVED** [review]
/approve

@khrm does the cli repo have guidance on how to extend `tkn` with plugins? Are we charting new territory here?

**Comment by khrm** [comment]
@adambkaplan We have already integrated with the hub cli. So no new unchartered territory here.

**Comment by khrm** [comment]
@enarha @sayan-biswas @alan-ghelardi We also want to merge this before the release.

**Review by sayan-biswas — APPROVED** [review]

**Review by vdemeester — COMMENTED** [review]
/lgtm

**Pull request merged**
