### PR TITLE
Add ppc64le support to Tekton results

### PR DESCRIPTION
**Pull request by snehakpersistent**
This PR is to track work on adding official Power support to Tekton results. 
I am able to build(using ko) and test api/watcher images natively on Power. Using these images I could successfully deploy Results on Power. I have added build and unit test jobs for ppc64le in the tekton pipeline in this PR. 
@wlynch @dibyom let me know your inputs on this.

### CODE REVIEW

**Comment by snehakpersistent** [comment]
@wlynch @dibyom any update on this?

**Review by dibyom — APPROVED** [review]
Thank you @snehakpersistent 
This looks good to me

**Comment by dibyom** [comment]
Error seems to be due to this:

tekton/release.yaml
  74:16     error    trailing spaces  (trailing-spaces)

**Comment by snehakpersistent** [comment]
@dibyom I have fixed the linting error. Please review it.

**Comment by enarha** [comment]
/kind feature
We need this label for release as discussed in the last WG call.

**Pull request merged**
