### PR TITLE
Remove TLS hostname override

### LINKED ISSUE #521: Liveness and Readiness probes fail with recommended certificate setup
# Expected Behavior
Expected that `tekton-results-api` pod would become healthy.

# Actual Behavior
The `tekton-results-api` pod does not become healthy. Readiness and Liveness probes fail with 503 response. Doing a port-forward on the `tekton-results-api`'s  `api` container and doing a curl to the `/healthz` endpoint returns the following error:

```
{"code":14,"message":"connection error: desc = \"transport: authentication handshake failed: x509: certificate is valid for tekton-results-api-service.tekton-pipelines.svc.cluster.local, not localhost\"","details":[]}
```

I am using self-signed certificates managed by certman. Adding `localhost` to the `dnsNames` list results in the Liveness and Readiness probes passing. As per [prerequisites](https://github.com/tektoncd/results/blob/e85794158c43defca77deb2b63201497dca9f45d/docs/install.md?plain=1#L27) this is not the recommended config.

# Steps to Reproduce the Problem

1. Install Certman
2. Install Tekton Pipelines (v0.38.4)
3. Create Certificate and Certificate issuer as below:
```yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: tekton-results-selfsigned-issuer
  namespace: tekton-pipelines
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tekton-results-tls-cert
  namespace: tekton-pipelines
spec:
  dnsNames:
  - tekton-results-api-service.tekton-pipelines.svc.cluster.local
  # - localhost # uncomment this to make probes pass
  issuerRef:
    kind: Issuer
    name: tekton-results-selfsigned-issuer
  secretName: tekton-results-tls
```
4. Install Tekton Results following all install instructions besides certificate generation (v0.7.0)
5. Observe unhealthy `tekton-results-api` pod

# Additional Info

- Kubernetes version:

```
Server Version: v1.23.17-eks-c12679a
```

- Tekton Pipeline version:

```
v0.38.4
```

### PR DESCRIPTION
**Pull request by sayan-biswas**
# Changes

Removes the TLS hostname override option and disables TLS verification for the internal gRPC client used for proxying incoming request to gRPC server.

Fixes #521 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you review them:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] [Tested your changes locally](https://github.com/tektoncd/results/blob/main/docs/DEVELOPMENT.md) (if this is a code change)
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user-facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contain the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
ACTION REQUIRED: Config option, TLS_HOSTNAME_OVERRIDE is removed as the internal gRPC proxy client doesn't need to reverify the TLS.
```

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/lgtm

**Comment by adambkaplan** [comment]
This should have an `ACTION REQUIRED` prefix on the release note. This introduces a "breaking" change by removing a deployment configuration option.

**Comment by sayan-biswas** [comment]
> This should have an `ACTION REQUIRED` prefix on the release note. This introduces a "breaking" change by removing a deployment configuration option.

Updated release note.

**Pull request merged**
