### PR TITLE
Vendoring and dependencies bump

### PR DESCRIPTION
**Pull request by vdemeester**
[Bump tektoncd/pipeline to 0.39.0…](https://github.com/tektoncd/results/commit/ad47222ba433dd4156d3d5c768ef41a84b6bc3a7)

… as well as linked dependencies (knative, k8s).
Also go to 1.18 in go.mod.

[Add vendor folder to results](https://github.com/tektoncd/results/commit/3a2858795e63005357bc381424d21c3caf9810ff)
One of the reason is to be consistent with the rest of the repository.

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

/cc @dibyom @adambkaplan

### CODE REVIEW

**Comment by vdemeester** [comment]
Vendoring is optional in my views, but I felt it would make sense to be consistent across the tektoncd components.

**Comment by vdemeester** [comment]
Requires https://github.com/tektoncd/plumbing/pull/1194 👼🏼

**Comment by vdemeester** [comment]
cc @afrittoli @dibyom @abayer  🐼

**Review by adambkaplan — APPROVED** [review]
/approve

**Comment by vdemeester** [comment]
huh… 🤔 why didn't prow accept @adambkaplan's approval.. he is an approver 🤔

**Comment by adambkaplan** [comment]
Need to rebase (odd because I thought prow fast forwards on top of main?)

**Comment by vdemeester** [comment]
@adambkaplan maybe now ? 👼🏼

**Comment by khrm** [comment]
/kind cleanup
We need this label for release as discussed in the last WG call.

**Pull request merged**
