### PR TITLE
Add watcher option logs_timestamps to store taskrun logs with timestamps

### PR DESCRIPTION
**Pull request by thomascube**
# Changes

Adds a watcher CLI argument `logs_timestamps` which is passed through to the `tektoncd/cli/pkg/options` to collect container logs with timestamps.

Requested in #671

/kind feature
# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you review them:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] [Tested your changes locally](https://github.com/tektoncd/results/blob/main/docs/DEVELOPMENT.md) (if this is a code change)
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [ ] Has a kind label. You can add a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user-facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contain the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
Add watcher option logs_timestamps to store taskrun logs with timestamps (#671)
```

### CODE REVIEW

**Comment by thomascube** [comment]
I couldn't find the right place to add tests for these changes as they basically pass through a cli argument. Please advise where I could add tests. Thanks!

**Review by khrm — COMMENTED** [review]
/ok-to-test

**Comment by khrm** [comment]
@thomascube Please sign the cla.

**Comment by thomascube** [comment]
@dibyom, @enarha, @khrm I have just rebased the PR. Could you please review?

**Pull request merged**
