### PR TITLE
Organize Results Kustomization with Components

### LINKED ISSUE #340: Use Kustomize components to create multiple "distributions"
### Feature request

Use Kustomize [Components](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/components.md) to create release variants for the following:

1. Default with no database
2. Default with postgres DB
3. Logs enabled with postgres DB and PVC storage

We could also provide example overlays as we add more backend providers.

### Use case

1. Create release YAML with the database undefined (could be consumed by the Operator?)
2. Create overlays for e2e testing of various configurations.

### PR DESCRIPTION
**Pull request by adambkaplan**
Utilize Kustomize Components [1] to create variants of Results. The Logs API introduces a potential explosion in configuration options. Releasing with Logs may require multiple changes to the deployment - some potentially incompatible. Components provides us a mechanism to manage the exploding test matrix. The config directory has been reorganized as follows:

- base |---- <base configuration manifests>
- components |---- local-db (deploys PostgresDB)
|---- metadata (common metadata and transformations)
- overlays |----- default-local-db (local PostgresDB, logs disabled)

Tests and releases are now based off of `overlays/default-local-db`. Future enhancements can add additional overlays for testing or community examples.

[1] https://github.com/kubernetes-sigs/kustomize/blob/master/examples/components.md

Fixes #340

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/approve

**Comment by adambkaplan** [comment]
/hold

This will conflict with #334, and I'd rather we default to GORM for migrating the database.

**Comment by khrm** [comment]
Do we need this for v0.5.0? @alan-ghelardi @adambkaplan ? Or should we just do a release without this?

**Comment by adambkaplan** [comment]
I wouldn't call this a hard requirement for release. That said, this PR will help downstream distributions/teams that don't want to run the database on Kubernetes.

**Comment by alan-ghelardi** [comment]
Agree with the Adam's statement.
/approve
/lgtm

**Review by khrm — COMMENTED** [review]
/test tekton-results-unit-tests

**Review by khrm — COMMENTED** [review]
/kind cleanup
We need this label for releasing as discussed in the last WG call.

**Pull request merged**
