### PR TITLE
Allow setting SSLMODE for connections to database by env variable

### PR DESCRIPTION
**Pull request by CathalOConnorRH**
Allow setting `SSLMODE` by setting environment variable
`DB_SSLMODE=verify-full`

https://www.postgresql.org/docs/current/libpq-ssl.html

### CODE REVIEW

**Review by imjasonh — APPROVED** [review]

**Comment by CathalOConnorRH** [comment]
@imjasonh Would you be able to LGTM this, it appears to have passed all tests?

**Pull request merged**
