### PR TITLE
Supports CreatedTime and UpdatedTime in Record.

### PR DESCRIPTION
**Pull request by XinruZhang**
Supports CreatedTime and UpdatedTime in Record.
    
This commit mainly aims to provide timestamp support when creating and updating a Record:

1. Adds CreatedTime and UpdatedTime in
  - proto definition
  - sql schema
  - gorm model definition
2. Modifies ToAPI and ToStorage to get the two timestamps work.
  - tests if the two fields can be properly transformed.
3. Updates the two fields when CreateRecord.
  - tests if the two fields are updated after the creation.
4. Updates the UpdateTime field when UpdateRecord.
  - tests if the UpdateTime field is updated after updating.

In addition, there are three minor changes:
1. To make the code structure more tidy, move TestMain from results_test.go to server_test.go
2. Solves a bug when comparing Error Code in UpdateRecord
3. Adjusts the indent in resources.proto

### CODE REVIEW

**Comment by XinruZhang** [comment]
/hold
reviewable, waiting for #25

**Review by wlynch — APPROVED** [review]
Looks great! :D 

/lgtm

**Comment by XinruZhang** [comment]
Unit tests failed because the newly merged PR  #34, therefore I ignored the updated_time and created_time field when testing watcher's behavior.

**Review by wlynch — APPROVED** [review]
/lgtm

**Pull request merged**
