### PR TITLE
Add golang ci linter

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
# Changes

- Add  golangci-lint to lint codebase. Most tekton projects uses this check.
- Handle some easy fixable lint issues.

# Out of the scope this pr.

Fixing all lint issues.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you review them:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] [Tested your changes locally](https://github.com/tektoncd/results/blob/main/docs/DEVELOPMENT.md) (if this is a code change)
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [ ] Has a kind label. You can add a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user-facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contain the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

### CODE REVIEW

**Comment by AndrienkoAleksandr** [comment]
Looks like github actions are disabled.

**Comment by AndrienkoAleksandr** [comment]
@dibyom do I have chance to merge this pull request ?

**Review by dibyom — APPROVED** [review]

**Review by khrm — COMMENTED** [review]
@dibyom We aren't using workflows/GH actions for linting in the other Tekton projects. Shouldn't we take a consistent approach and implement linting in the same way?

**Comment by khrm** [comment]
/hold

Let's wait for response before merging.

**Comment by AndrienkoAleksandr** [comment]
> @dibyom We aren't using workflows/GH actions for linting in the other Tekton projects. Shouldn't we take a consistent approach and implement linting in the same way?

@khrm, Strange I see the same github action for tekton-chains: https://github.com/tektoncd/chains/blob/main/.github/workflows/lint.yaml and https://github.com/tektoncd/chains/actions/runs/4952394643/jobs/8858626717?pr=801


For tekton-pipeline I see lint config https://github.com/tektoncd/pipeline/blob/main/.golangci.yml, but I don't see where is ci configs.

**Comment by AndrienkoAleksandr** [comment]
Looks like  ci dogfooding configuration stored here https://github.com/tektoncd/plumbing ...

**Comment by AndrienkoAleksandr** [comment]
I see there is pipelinerun https://github.com/tektoncd/plumbing/blob/main/tekton/ci/jobs/tekton-golang-lint.yaml

**Comment by AndrienkoAleksandr** [comment]
Also I see usage of this lint check for plumbing project https://github.com/tektoncd/plumbing/blob/main/tekton/ci/repos/plumbing/template.yaml#LL102C9-L102C9 . But when I open any pull request from this project, I see this lint ci check is absent. So I'm confused how it works...

**Comment by khrm** [comment]
@AndrienkoAleksandr Please check this pr: https://github.com/tektoncd/results/pull/493 

We generally use Makefile for Triggers, Pipelines, etc.

**Comment by khrm** [comment]
Workflows are disable because of some issue.

**Comment by AndrienkoAleksandr** [comment]
Close on favor https://github.com/tektoncd/results/pull/493

**Pull request closed without merging**
