### PR TITLE
improve watcher logs

### PR DESCRIPTION
**Pull request by ramessesii2**
- improve watcher logs messages

/kind cleanup

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you review them:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] [Tested your changes locally](https://github.com/tektoncd/results/blob/main/docs/DEVELOPMENT.md) (if this is a code change)
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user-facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contain the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

### CODE REVIEW

**Comment by ramessesii2** [comment]
cc @sayan-biswas

**Comment by enarha** [comment]
@ramessesii2 personally I like we have the name and the namespace as separate fields as having the combo in "knative.dev/key" is less obvious. I agree the kind is probably redundant as it's quite obvious from the "results.tekton.dev/kind" field. That's IMO. Having said that, I do not have strong objection, so if others prefer the shorter records, then OK with me.

**Review by avinal — CHANGES_REQUESTED** [review]
+1 to Emil. Although it may seem that the fields are redundant. Having explicit common fields like name, namespace, and kind is preferable and direct. In an ideal case, a user/log parser will look out for well-known fields than a less common field injected by the knative framework.

So, IMO we should leave them as it is. The message improvement is necessary and appreciated, and if you find more instances for improvement, please do that.

**Comment by ramessesii2** [comment]
@enarha @avinal given your reviews, I propose having the keys 'namespace' & 'name' uniform throughout the watcher logs. Right now, it's sporadic. 
Also, we seem to agree having "results.tekton.dev/kind" is enough for marking a `kind` in logs, so I'll get rid of `kind` keys.

**Review by avinal — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
