### PR TITLE
Update database drivers

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Update the database drivers

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/ok-to-test

**Comment by gabemontero** [comment]
/assign @khrm 
/assign @sayan-biswas 
/assign @avinal 
/assign @enarha 
see https://github.com/jackc/pgx/commit/26c79eb215cd1a8022fee209e1df9601626d2f89 

what will it take to get this approved / merged?

**Comment by avinal** [comment]
I will test it today and put my review.

**Review by khrm — COMMENTED** [review]
/lgtm

**Comment by khrm** [comment]
@avinal This updating only vendored code. If there is an issue, it would have been caught by e2e tests.

**Review by avinal — APPROVED** [review]
Yes Khurram I saw it after opening the changes. Good to go
/approve
/lgtm

**Pull request merged**
