### PR TITLE
Bump go version to 1.19

### LINKED ISSUE #443: E2E tests use functions not available in go 1.18
# Expected Behavior

E2E tests should compile and pass when using go 1.18.x 

# Actual Behavior

The tests fail to compile because it uses one function that is not available in go 1.18. Refer:

https://github.com/tektoncd/results/blob/fdc47542cc0ce52fadaa4389a01ff0c2b75fe6e5/test/e2e/client/rest.go#L117

```sh
# github.com/tektoncd/results/test/e2e/client
client/rest.go:117:13: c.url.JoinPath undefined (type *url.URL has no field or method JoinPath)
FAIL    github.com/tektoncd/results/test/e2e [build failed]
```

Go mod file:

https://github.com/tektoncd/results/blob/fdc47542cc0ce52fadaa4389a01ff0c2b75fe6e5/go.mod#L3

Minimum go version required for this function is [1.19](https://pkg.go.dev/net/url@go1.19#URL.JoinPath) 

# Steps to Reproduce the Problem

1. Pull the latest commit 
2. Run `go version`. It should be 1.18.x
3. Run `./test/e2e-tests.sh`
4. See the error

# Additional Info
- Refer: [net/url package documentation for go1.18.10](https://pkg.go.dev/net/url@go1.18.10)
- Refer: [net/url package documentation for go1.19](https://pkg.go.dev/net/url@go1.19#URL.JoinPath)

### PR DESCRIPTION
**Pull request by avinal**
# Changes

- go1.18 support has already ended on 1 Feb 2023
- We are using functions in our tests that are not available in 1.18
- Fixes #443

/kind bug
# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you review them:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] [Tested your changes locally](https://github.com/tektoncd/results/blob/main/docs/DEVELOPMENT.md) (if this is a code change)
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user-facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contain the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
Minimum go version requirement updated to go1.19
```

### CODE REVIEW

**Comment by avinal** [comment]
Should I update other dependencies as well?

**Comment by adambkaplan** [comment]
Have you run `go mod tidy` and `go mod vendor`? I am somewhat surprised that changing the `go.mod` compatibility hasn't introduced any changes to `go.mod` and `go.sum`.

**Comment by adambkaplan** [comment]
(also interesting that we aren't checking that `go.mod` and `go.sum` are up to date/accurate).

**Comment by avinal** [comment]
Yes, I ran both the commands. I can bump the dependencies manually, though. If we want that.

**Review by khrm — COMMENTED** [review]
Change type from bug to misc.

/kind misc

**Pull request merged**
